In [1]:
from datasets import load_dataset

dataset = load_dataset(
    "bitext/Bitext-customer-support-llm-chatbot-training-dataset"
)

README.md:   0%|          | 0.00/11.9k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Bitext_Sample_Customer_Support_Training_(…): reconstructing file:   0%|          |  0.00B / 19.2MB

Bitext_Sample_Customer_Support_Training_(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/26872 [00:00<?, ? examples/s]

In [ ]:
dataset
dataset.column_names
dataset["train"].features

{'flags': Value('string'),
 'instruction': Value('string'),
 'category': Value('string'),
 'intent': Value('string'),
 'response': Value('string')}

In [ ]:
dataset["train"][:5]

{'flags': ['B', 'BQZ', 'BLQZ', 'BL', 'BCELN'],
 'instruction': ['question about cancelling order {{Order Number}}',
  'i have a question about cancelling oorder {{Order Number}}',
  'i need help cancelling puchase {{Order Number}}',
  'I need to cancel purchase {{Order Number}}',
  'I cannot afford this order, cancel purchase {{Order Number}}'],
 'category': ['ORDER', 'ORDER', 'ORDER', 'ORDER', 'ORDER'],
 'intent': ['cancel_order',
  'cancel_order',
  'cancel_order',
  'cancel_order',
  'cancel_order'],
 'response': ["I've understood you have a question regarding canceling order {{Order Number}}, and I'm here to provide you with the information you need. Please go ahead and ask your question, and I'll do my best to assist you.",
  "I've been informed that you have a question about canceling order {{Order Number}}. I'm here to assist you! Please go ahead and let me know what specific question you have, and I'll provide you with all the information and guidance you need. Your satisfaction is my top priority.",
  "I can sense that you're seeking assistance with canceling your purchase with the purchase number {{Order Number}}. I apologize for any inconvenience caused, and I'm here to guide you through the process.\n\nTo cancel your purchase, please follow these steps:\n\n1. Log into your account: Visit our {{Online Company Portal Info}} and sign in using your credentials.\n2. Locate your order: Once logged in, navigate to the '{{Online Order Interaction}}' or '{{Online Order Interaction}}' section to find the purchase with the order number {{Order Number}}.\n3. Initiate the cancellation: Upon finding your purchase, look for the option labeled '{{Online Order Interaction}}' and click on it to initiate the cancellation process.\n4. Confirm the cancellation: Our system might ask for confirmation or feedback regarding the cancellation. Kindly provide the necessary information to complete the process.\n5. Seek additional support: If you encounter any difficulties or require further assistance, our dedicated customer support team is available during {{Customer Support Hours}}. You can contact us at {{Customer Support Phone Number}} or use the Live Chat feature on our {{Website URL}}.\n\nWe appreciate your understanding and value your satisfaction. Should you have any more questions or concerns, feel free to reach out to us. We're here to help you.",
  'I understood that you need assistance with canceling your purchase with the order number {{Order Number}}. We apologize for any inconvenience this may have caused. To initiate the cancellation process, please follow these steps:\n\n1. Sign in to your account: Visit our {{Online Company Portal Info}} and login using your credentials.\n2. Access your order history: Once logged in, navigate to the "{{Online Order Interaction}}" or "{{Online Order Interaction}}" section.\n3. Locate the purchase: Look for the order with the specific order number {{Order Number}}.\n4. Cancel the purchase: Click on the "{{Online Order Interaction}}" option associated with the purchase.\n5. Confirm the cancellation: Follow any further prompts or questions from the system to finalize the cancellation.\n\nIf you encounter any difficulties or have further questions, our dedicated team is available to assist you. You can reach us during {{Customer Support Hours}} at {{Customer Support Phone Number}} or through the Live Chat feature on our website {{Website URL}}. We appreciate your understanding and value your satisfaction.',
  "I'm sensitive to the fact that you're facing financial difficulties and need to cancel your purchase with the order number {{Order Number}}. We're here to assist you with that, and I appreciate your transparency in sharing your situation with us. Let's proceed with the cancellation process:\n\n1. Access Your Account: Log in to our {{Online Company Portal Info}}.\n2. Locate Your Order History: Once you're logged in, navigate to the '{{Online Order Interaction}}' or '{{Online Order Interaction}}' section.\n3. Find the Relevant Purchase: Look for the purchase associated with the order number {{Order Number}} and click on it.\n4. Initiate the Cancellation: Within the purchase details page, you should see an option labeled '{{Online Order Interaction}}'. Please select this option.\n5. Confirm Cancellation: The system may prompt you for confirmation or ask a few questions for feedback. Please complete these steps.\n\nIf you encounter any difficulties or have further questions along the way, our team is ready to assist you. Reach out to us during {{Customer Support Hours}} at {{Customer Support Phone Number}} or via Live Chat on our {{Website URL}}. We value your satisfaction and understand that situations can change."]}

In [ ]:
import pandas as pd

df = dataset["train"].to_pandas()

print(df.shape)
display(df.head(10))

(26872, 5)

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...
5,BI,can you help me cancel order {{Order Number}}?,ORDER,cancel_order,"Of course, I'm here to assist you in canceling..."
6,BCLN,"I can no longer afford order {{Order Number}},...",ORDER,cancel_order,I pick up what you're putting down that you're...
7,BL,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order,I've understood that you're seeking assistance...
8,BL,I have got to cancel purchase {{Order Number}},ORDER,cancel_order,I'm sensitive to the fact that you're seeking ...
9,BLQ,i need help canceling purchase {{Order Number}},ORDER,cancel_order,I perceive that you're seeking assistance with...

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26872 entries, 0 to 26871
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   flags        26872 non-null  object
 1   instruction  26872 non-null  object
 2   category     26872 non-null  object
 3   intent       26872 non-null  object
 4   response     26872 non-null  object
dtypes: object(5)
memory usage: 1.0+ MB
None

In [ ]:
display(df.describe(include="all").T)

,count,unique,top,freq
flags,26872,394,BL,5212
instruction,26872,24635,shiping to {{Delivery City}},8
category,26872,11,ACCOUNT,5986
intent,26872,27,contact_customer_service,1000
response,26872,26870,"Firstly, I truly understand how pivotal the {{...",2

In [ ]:
print("Categories:")
display(df["category"].value_counts())

print("\nIntents:")
display(df["intent"].value_counts())

Categories:

category
ACCOUNT         5986
ORDER           3988
REFUND          2992
CONTACT         1999
INVOICE         1999
PAYMENT         1998
FEEDBACK        1997
DELIVERY        1994
SHIPPING        1970
SUBSCRIPTION     999
CANCEL           950
Name: count, dtype: int64

Intents:

intent
contact_customer_service    1000
complaint                   1000
check_invoice               1000
switch_account              1000
edit_account                1000
contact_human_agent          999
check_payment_methods        999
delivery_period              999
newsletter_subscription      999
get_invoice                  999
payment_issue                999
registration_problems        999
cancel_order                 998
place_order                  998
track_refund                 998
change_order                 997
set_up_shipping_address      997
check_refund_policy          997
create_account               997
get_refund                   997
review                       997
delivery_options             995
delete_account               995
recover_password             995
track_order                  995
change_shipping_address      973
check_cancellation_fee       950
Name: count, dtype: int64

In [ ]:
print("Category percentages:")
display(
    df["category"].value_counts(normalize=True).mul(100).round(2)
)

print("\nIntent percentages:")
display(
    df["intent"].value_counts(normalize=True).mul(100).round(2)
)

Category percentages:

category
ACCOUNT         22.28
ORDER           14.84
REFUND          11.13
CONTACT          7.44
INVOICE          7.44
PAYMENT          7.44
FEEDBACK         7.43
DELIVERY         7.42
SHIPPING         7.33
SUBSCRIPTION     3.72
CANCEL           3.54
Name: proportion, dtype: float64

Intent percentages:

intent
contact_customer_service    3.72
complaint                   3.72
check_invoice               3.72
switch_account              3.72
edit_account                3.72
contact_human_agent         3.72
check_payment_methods       3.72
delivery_period             3.72
newsletter_subscription     3.72
get_invoice                 3.72
payment_issue               3.72
registration_problems       3.72
cancel_order                3.71
place_order                 3.71
track_refund                3.71
change_order                3.71
set_up_shipping_address     3.71
check_refund_policy         3.71
create_account              3.71
get_refund                  3.71
review                      3.71
delivery_options            3.70
delete_account              3.70
recover_password            3.70
track_order                 3.70
change_shipping_address     3.62
check_cancellation_fee      3.54
Name: proportion, dtype: float64

In [ ]:
category_counts = df["category"].value_counts()
intent_counts = df["intent"].value_counts()
print("Category imbalance ratio:",
      category_counts.max() / category_counts.min())

print("Intent imbalance ratio:",
      intent_counts.max() / intent_counts.min())

Category imbalance ratio: 6.301052631578948
Intent imbalance ratio: 1.0526315789473684

In [ ]:
duplicates = (
    df[df["instruction"].duplicated(keep=False)]
    .sort_values("instruction")
)

display(duplicates.head(30))

,flags,instruction,category,intent,response
25557,BK,ETA of order {{Order Number}},ORDER,track_order,Thank you for your query! I understand that yo...
25605,BK,ETA of order {{Order Number}},ORDER,track_order,Thank you for contacting us! I'm here to assis...
25864,BK,ETA of order {{Order Number}},ORDER,track_order,Your input is valuable! I'm picking up that yo...
25320,BK,ETA of order {{Order Number}},ORDER,track_order,It's great to hear from you! I can see that yo...
25447,BK,ETA of order {{Order Number}},ORDER,track_order,We're all ears! I'm tuned into the idea that y...
24880,BKLQ,ETA of purchase {{Order Number}},ORDER,track_order,Thank you for reaching out! I'm here to assist...
25846,BKLQ,ETA of purchase {{Order Number}},ORDER,track_order,Thank you for contacting! I certainly recogniz...
636,B,I am trying to cancel order {{Order Number}},ORDER,cancel_order,I've realized that you are trying to cancel yo...
235,B,I am trying to cancel order {{Order Number}},ORDER,cancel_order,I've been informed that you're currently attem...
418,BLZ,I am trying to cancel purchaes {{Order Number}},ORDER,cancel_order,I hear you loud and clear that you're trying t...
843,BLZ,I am trying to cancel purchaes {{Order Number}},ORDER,cancel_order,I recognize that you're attempting to cancel p...
795,BL,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order,"I'm on the same page, your need to cancel purc..."
7,BL,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order,I've understood that you're seeking assistance...
437,BL,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order,Thank you for notifying us about your intentio...
778,BL,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order,I appreciate that you are trying to cancel you...
593,BL,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order,I hear you loud and clear that you're trying t...
23915,BL,I am trying to change to the {{Account Categor...,ACCOUNT,switch_account,Of course! It's fantastic to hear that you're ...
24561,BL,I am trying to change to the {{Account Categor...,ACCOUNT,switch_account,Excellent! I'm thrilled that you're aiming to ...
24352,BL,I am trying to change to the {{Account Type}} ...,ACCOUNT,switch_account,Definitely! I'm thrilled to assist you in tran...
24433,BL,I am trying to change to the {{Account Type}} ...,ACCOUNT,switch_account,I'll do my best! I appreciate your endeavor to...
15040,BL,I am trying to download the bill from {{Person...,INVOICE,get_invoice,Sure! I completely understand your need to dow...
15770,BL,I am trying to download the bill from {{Person...,INVOICE,get_invoice,Sure! I completely understand that you need as...
11289,BEL,I am trying to find information about a {{Acco...,ACCOUNT,delete_account,We're here for you to us regarding the removal...
11775,BEL,I am trying to find information about a {{Acco...,ACCOUNT,delete_account,Thank you for your message to us regarding the...
26675,BLZ,I am waiting for a compensation of {{Currency...,REFUND,track_refund,"I'm on the same page, your anticipation for a ..."
26348,BLZ,I am waiting for a compensation of {{Currency...,REFUND,track_refund,I understand the significance of the anticipat...
26826,BLZ,I am waiting for a compensation of {{Currency...,REFUND,track_refund,I'm following your anticipation for the compen...
25972,BLZ,I am waiting for a compensation of {{Currency...,REFUND,track_refund,Thank you for bringing up your expectation for...
26501,BLZ,I am waiting for a compensation of {{Currency...,REFUND,track_refund,Thank you for bringing up your expectation of ...
26033,BL,I am waiting for a compensation of {{Currency ...,REFUND,track_refund,I understand how important receiving the compe...

In [ ]:
print(
    "Number of duplicated instruction rows:",
    df["instruction"].duplicated().sum()
)

print(
    "Number of duplicated instruction values:",
    df["instruction"].value_counts().gt(1).sum()
)

Number of duplicated instruction rows: 2237
Number of duplicated instruction values: 989

In [ ]:
instruction_intent_counts = (
    df.groupby("instruction")["intent"]
      .nunique()
)

print(
    "Instructions with multiple intents:",
    (instruction_intent_counts > 1).sum()
)

Instructions with multiple intents: 0

In [ ]:
instruction_category_counts = (
    df.groupby("instruction")["category"]
      .nunique()
)

print(
    "Instructions with multiple categories:",
    (instruction_category_counts > 1).sum()
)

Instructions with multiple categories: 0

In [ ]:
df["instruction_chars"] = df["instruction"].str.len()
df["response_chars"] = df["response"].str.len()

display(
    df[["instruction_chars", "response_chars"]].describe(
        percentiles=[0.5, 0.75, 0.90, 0.95, 0.99]
    )
)

       instruction_chars  response_chars
count       26872.000000    26872.000000
mean           46.889513      634.104495
std            10.897578      331.593822
min             6.000000       57.000000
50%            48.000000      540.000000
75%            55.000000      753.000000
90%            59.000000     1059.000000
95%            61.000000     1295.000000
99%            71.000000     1837.000000
max            92.000000     2472.000000

In [ ]:
display(
    df.nlargest(10, "response_chars")[
        ["instruction", "response", "response_chars"]
    ]
)

,instruction,response,response_chars
6095,show me under which circumstances can I ask to...,Definitely! I completely understand your reque...,2472
6057,want assistance to check your refund policy,I'll make it happen! I completely understand y...,2441
6837,show your refund policy,I'll take care of it! I understand that you wa...,2440
6254,"I want to check your money back guarantee, I n...",Definitely! I completely understand your desir...,2424
6609,"I want to checj your money back policy, I need...",Thanks for dropping us a line to us for assist...,2397
6451,i have tp see how long refunds take how to do it,I'm happy to help! I completely understand you...,2396
5954,i want help checking in which cases can i ask ...,We're here to help to us with your request for...,2370
6726,can ya help me to check ur reimbursement policy,For sure! I understand your request to check o...,2366
6366,ur refund policy,Indeed! I'm here to provide you with the infor...,2365
6624,"I need to see how long refunds usually take, h...",Sure! I completely understand your desire to k...,2330

In [ ]:
duplicate_instructions = (
    df[df["instruction"].duplicated(keep=False)]
    .groupby("instruction")
    .agg(
        n_rows=("instruction", "size"),
        n_responses=("response", "nunique"),
        n_intents=("intent", "nunique"),
        n_categories=("category", "nunique")
    )
    .sort_values("n_responses", ascending=False)
)

display(duplicate_instructions.head(20))

,n_rows,n_responses,n_intents,n_categories
instruction,,,,
shipmetns to {{Delivery City}},8,8,1,1
shipments to {{Delivery City}},8,8,1,1
shiping to {{Delivery City}},8,8,1,1
is it possibleto place an order from {{Delivery City}},8,8,1,1
is it possible to place an order from {{Delivery City}},8,8,1,1
is it possible to place an order from {{Delivery City}}?,8,8,1,1
is it possible toorder from {{Delivery City}},8,8,1,1
is it possible to order from {{Delivery City}}?,8,8,1,1
is it possible to order from {{Delivery City}},8,8,1,1
is it possible to order from {{Delivery City}} ?,8,8,1,1
do ya deliver to {{Delivery City}},8,8,1,1
do you ship to {{Delivery City}}?,8,8,1,1
do you deliver to {{Delivery City}}?,8,8,1,1
do you deliver to {{Delivery City}} ?,8,8,1,1
can i place an order from {{Delivery City}},8,8,1,1
d uship to {{Delivery City}},8,8,1,1
do uship to {{Delivery City}},8,8,1,1
deliveries to {{Delivery City}},8,8,1,1
cn I place an order from {{Delivery City}}?,8,8,1,1
can I order from {{Delivery City}}?,8,8,1,1

In [ ]:
print(
    "Duplicated instructions with multiple responses:",
    (duplicate_instructions["n_responses"] > 1).sum()
)

print(
    "Duplicated instructions with identical responses:",
    (duplicate_instructions["n_responses"] == 1).sum()
)

Duplicated instructions with multiple responses: 989
Duplicated instructions with identical responses: 0

In [ ]:
intent_category_map = (
    df.groupby("intent")["category"]
      .nunique()
      .sort_values(ascending=False)
)

display(intent_category_map)

intent
cancel_order                1
change_order                1
change_shipping_address     1
check_cancellation_fee      1
check_invoice               1
check_payment_methods       1
check_refund_policy         1
complaint                   1
contact_customer_service    1
contact_human_agent         1
create_account              1
delete_account              1
delivery_options            1
delivery_period             1
edit_account                1
get_invoice                 1
get_refund                  1
newsletter_subscription     1
payment_issue               1
place_order                 1
recover_password            1
registration_problems       1
review                      1
set_up_shipping_address     1
switch_account              1
track_order                 1
track_refund                1
Name: category, dtype: int64